INSERT INTO paises (id, nombre, codigo_iso, moneda_local, simbolo_moneda, formato_moneda, emoji_bandera) VALUES
(1, 'México', 'MX', 'Peso mexicano', '$', '$#,##0.00', 'https://flagcdn.com/mx.svg'),
(2, 'Canadá', 'CA', 'Dólar canadiense', '$', '$#,##0.00', 'https://flagcdn.com/ca.svg'),
(3, 'Estados Unidos', 'US', 'Dólar estadounidense', '$', '$#,##0.00', 'https://flagcdn.com/us.svg'),
(4, 'Venezuela', 'VE', 'Bolívar digital', 'Bs.', 'Bs#,##0.00', 'https://flagcdn.com/ve.svg'),
(5, 'Colombia', 'CO', 'Peso colombiano', '$', '$#,##0.00', 'https://flagcdn.com/co.svg'),
(6, 'Perú', 'PE', 'Sol peruano', 'S/', 'S/#,##0.00', 'https://flagcdn.com/pe.svg'),
(7, 'Chile', 'CL', 'Peso chileno', '$', '$#,##0.00', 'https://flagcdn.com/cl.svg'),
(8, 'Ecuador', 'EC', 'Dólar estadounidense', '$', '$#,##0.00', 'https://flagcdn.com/ec.svg'),
(9, 'República Dominicana', 'DO', 'Peso dominicano', 'RD$', 'RD$#,##0.00', 'https://flagcdn.com/do.svg'),
(10, 'Argentina', 'AR', 'Peso argentino', '$', '$#,##0.00', 'https://flagcdn.com/ar.svg'),
(11, 'Brasil', 'BR', 'Real brasileño', 'R$', 'R$#,##0.00', 'https://flagcdn.com/br.svg'),
(12, 'España', 'ES', 'Euro', '€', '€#,##0.00', 'https://flagcdn.com/es.svg'),
(13, 'Alemania', 'DE', 'Euro', '€', '€#,##0.00', 'https://flagcdn.com/de.svg'),
(14, 'Reino Unido', 'GB', 'Libra esterlina', '£', '£#,##0.00', 'https://flagcdn.com/gb.svg'),
(15, 'Japón', 'JP', 'Yen japonés', '¥', '¥#,##0', 'https://flagcdn.com/jp.svg'),
(16, 'Rusia', 'RU', 'Rublo ruso', '₽', '₽#,##0.00', 'https://flagcdn.com/ru.svg'),
(17, 'China', 'CN', 'Yuan chino', '¥', '¥#,##0.00', 'https://flagcdn.com/cn.svg');