INSERT INTO instruments_types_catalog (id, name) VALUES
(1, 'Ahorro'),
(2, 'Gasto'),
(3, 'Inversión');

INSERT INTO instruments_subtypes_catalog (id_instrument_type, name) VALUES
(1, 'Cuenta de ahorro'),
(1, 'Cuenta corriente'),
(1, 'Efectivo para ahorro'),
(2, 'TDC - Tarjeta de crédito'),
(2, 'TDD - Tarjeta de débito'),
(2, 'Efectivo para gastos'),
(3, 'Cuenta de inversión');
(1, 'SOFIPOS'),
(1, 'CDTs'),
(1, 'Fiducias de inversión'),
(1, 'Fondos de inversión colectiva'),
(1, 'Acciones'),
(1, 'Bonos corporativos'),
(1, 'Bonos gubernamentales'),
(1, 'Planes de pensiones'),
(1, 'Otros'),
(2, 'Créditos personales'),
(2, 'Créditos de libre inversión'),
(2, 'Créditos hipotecarios'),
(2, 'Créditos de vehículo'),
(2, 'Créditos educativos'),
(2, 'Microcréditos'),
(2, 'Otros'),
(3, 'Planes de ahorro programado'),
(3, 'Planes de ahorro voluntario'),
(3, 'Planes de ahorro para el retiro'),
(3, 'Planes de ahorro para la educación'),
(3, 'Planes de ahorro para la vivienda'),
(3, 'Otros');
